project: fuel
current_milestone: '5.1'
# For debug. Proceed only limited amount of items in project
trunc_report: 0
cache_dir: cache
use_auth: True
teams:
  python:
    fuel-python
    alekseyk-ru
    dshulyak
    rustyrobot
    ikalnitsky
    nmarkov
    aroma-x
    akislitsky
    kozhukalov
    lux-place
  ui:
    fuel-ui
    vkramskikh
    astepanchuk
    bdudko
    kpimenova
    jkirnosova
  library:
    fuel-library
    sgolovatiuk
    xenolog
    adidenko
    raytrac3r
    idv1985
    bogdando
    vkuklin
    sbogatkin
  l2:
    manashkin
    ekozhemyakin
  astute:
    fuel-astute
    vsharshov
  osci:
    fuel-osci
    sotpuschennikov
    dburmistrov
    vparakhin
    r0mikiam
    mrasskazov
  qa:
    fuel-qa
    apalkina
    aurlapova
    tatyana-leontovich
    asledzinskiy
    apanchenko-8
    ykotko
  devops:
    fuel-devops
    afedorova
    teran
    acharykov
  us:
    dborodaenko
    rmoe
    xarses
    dreidellhasa
  mos:
    mos-linux
    mos-neutron
    mos-nova
    mos-horizon
    mos-ceilometer
    mos-oslo
    mos-sahara
    iberezovskiy
  partners:
    izinovik
