project: fuel
# For debug. Proceed only limited amount of items in project
trunc_report: 0
cache_dir: cache
use_auth: True
teams:
  dpyzhov:
    fuel-python
    alekseyk-ru
    dshulyak
    rustyrobot
    ikalnitsky
    nmarkov
    aroma-x
    akislitsky
    kozhukalov
    lux-place
    dpyzhov
    a-gordeev
    ivankliuk
    vsharshov
    fuel-astute
    fuel-provisioning
    fuel-build
  vkramskikh:
    fuel-ui
    vkramskikh
    astepanchuk
    bdudko
    kpimenova
    jkirnosova
  vkuklin:
    fuel-library
    xenolog
    adidenko
    raytrac3r
    idv1985
    dmy-ilyin
    vkuklin
    sbogatkin
    xdeller
    andreika-mail
    omolchanov
    bpiotrowski
    sgolovatiuk
    bogdando
    smakar
  manashkin:
    manashkin
    ekozhemyakin
    akolesnikov
    fsoppelsa
    sovsianikov
  rvyalov:
    fuel-osci
    sotpuschennikov
    dburmistrov
    vparakhin
    r0mikiam
    mrasskazov
    dkaiharodsev
    heos
    asilenkov
  aurlapova:
    fuel-qa
    apalkina
    aurlapova
    tatyana-leontovich
    asledzinskiy
    apanchenko-8
    ykotko
    komelchenko
    ddmitriev
    dtyzhnenko
    unbelll
    ishamrai
  ishishkin:
    fuel-devops
    afedorova
    teran
    acharykov
    skulanov
    corepb
    mmatuszkowiak
    ibelikov
  dborodaenko:
    dborodaenko
    rmoe
    xarses
    dreidellhasa
    docaedo
    dshafer
  msemenov:
    mos-linux
    apodrepniy
    kdanylov
    msemenov
    asheplyakov
    asyriy
    vlos
    amogylchenko
    pboldin
  imarnat:
    mos-neutron
    mos-keystone
    mos-nova
    mos-horizon
    mos-ceilometer
    mos-oslo
    mos-sahara
    mos-heat
    mos-cinder
    mos-murano
    mos-glance
    mos-deployment
    mos-infra
    degorenko
    iberezovskiy
    e0ne
    dmitrymex
    smurashov
    rpodolyaka
    skolekonov
    vrovachev
    ylobankov
    alexei-kornienko
    aepifanov
    akamyshnikova
    dbelova
    efedorova
    enikanorov
    iyozhikov
    shakhat
    mdurnosvistov
    ruhe
    smelikyan
    skolekonov
    skraynev
    sreshetniak
    tnurlygayanov
    tsufiev-x
    yorik-sar
    mmaxur
    maxmazurenka
    teselkin-d
    obondarev
    akuznetsova
    i159
    akurilin
    pkholkin
    ekudryashova
    akhivin
    anevenchannyy
    iudovichenko
    sgalkin
    vryzhenkin
    vsaienko
  eshumakher:
    fuel-partner
    eshumakher
    izinovik
    gcon-monolake
    igajsin
    moshele
    aviramb
    srogov
    ekorekin
    ipovolotskaya
    azemlyanov
    nuritv
    popovych-andrey
    vstruk
  tnapierala:
    tzn
    salmon
    ksambor
    prmtl
    loles
    pkaminski
    maciej-iai
    romcheg
    sbrzeczkowski
  nbogdanov:
    nikolay-bogdanov
  external:
    longgeek
    berendt
    jesse-pretorius
    sammiestoel
    afly
    gilmeir-d
    mgariepy
    rherzallah
  other_mirantis:
    zynzel
    vpleshakov
    vdenisov
    nikishov-da
    atarasov
    agasanoff
    slava-val-al
    gleb-q
    dukov
    daniele-pizzolli
    iwi
    dtrishkin
    jvarigina
    tsipa740
    swann-w
  docs:
    fuel-docs
    evkonstantinov
